### ISSUE TITLE
[flann] Build step `make doc` fails

### ISSUE THREAD

**Issue by iFreilicht** [acxz/pkgbuilds#120] opened 2021-03-29 16:38 UTC
I've tried to build the flann package from the AUR directly, and the whole build works, except for the `make doc` step:

```
[100%] Built target flann
Scanning dependencies of target doc
[ 40%] Generating manual.tex
[ 40%] Generating images/cmake-gui.png
[ 60%] Generating manual.pdf
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
make[3]: *** [doc/CMakeFiles/doc.dir/build.make:86: doc/manual.pdf] Error 1
make[2]: *** [CMakeFiles/Makefile2:449: doc/CMakeFiles/doc.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:456: doc/CMakeFiles/doc.dir/rule] Error 2
make: *** [Makefile:322: doc] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

I modified my local PKGBUILD and removed the line `make doc`, see the patch below:

```
diff --git a/PKGBUILD b/PKGBUILD
index 088a408..40a38db 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -43,7 +43,6 @@ build() {
       -DBUILD_TESTS=OFF \
       -DBUILD_EXAMPLES=OFF
   make
-  make doc
 }
 
 package() {
```

Obviously, this is just a workaround, not a solution, but running `make doc` directly from `src/` yields the same output as what I pasted above, so I'm not sure how to troubleshoot.

**Comment by acxz** [comment] 2021-06-14 20:47
@iFreilicht Sorry for getting back to you late on this.

Are you still facing this problem?

I am not able to replicate it. If you still are facing this problem, then I'll go ahead and remove the `make doc` step as thats really necessary for the package itself.

If I dont hear back in a week, I'll go ahead and close this issue without taking an further action.

**Comment by iFreilicht** [comment] 2021-06-15 08:57
I didn't try to install it again. Maybe this was just a temporary issue with packages on my system. I'll try to test this again this week to make sure.

**Comment by acxz** [comment] 2021-07-01 21:29
Closing this issue, due to not being able to reproduce and inactivity.

**Closed by acxz** 2021-07-01 21:29 UTC
