### ISSUE TITLE
[qgroundcontrol] missing version string

### ISSUE THREAD

**Issue by q-wertz** [acxz/pkgbuilds#194] opened 2022-06-02 09:33 UTC
Not sure if this is an error of the AUR package but there is no/a wrong version string in the interface 
![image](https://user-images.githubusercontent.com/20948931/171601062-64081200-c70c-4c58-85d7-3d40a3c2981a.png)

**Comment by acxz** [comment] 2022-06-03 16:01
I can reproduce on the AUR package

**Comment by acxz** [comment] 2022-06-03 16:14
I can't run the AppImage on archlinux, if you can run the AppImage on another system and report if the issue is reproducible on the AppImage that would be great. Could also be expected since we are building a release version and not a daily build of QGroundControl.

**Comment by q-wertz** [comment] 2022-06-05 07:03
Thanks for confirmation.

Currently on holidays, can try in about 10 days

**Comment by q-wertz** [comment] 2022-06-19 07:45
Sorry for the long delay. In Manjaro I can run the AppImage and everything seems to be fine.
![image](https://user-images.githubusercontent.com/20948931/174471011-c9bb4268-2134-4c54-ab1a-c5e6922c0cb2.png)

**Comment by acxz** [comment] 2022-06-19 12:12
were u able to run the appimage on archlinux? I imagine our build process is neglecting the version somehow.

**Comment by q-wertz** [comment] 2022-06-19 13:50
I only have manjaro which is kind of archlinux, but there it runs well, yes.

**Comment by q-wertz** [comment] 2022-06-19 14:26
Colleague also checked the AppImage it on Ubuntu -> There it also shows the version string.

**Comment by acxz** [comment] 2022-08-08 00:15
kk, issue should be resolved with e0c63c9

**Closed by acxz** 2022-08-08 00:15 UTC
Labels: bug

**Comment by q-wertz** [comment] 2022-08-09 11:00
Can confirm it is fixed :+1: thanks
