### ISSUE TITLE
[python-pyqt5-sip4] Compilation Error

### ISSUE THREAD

**Issue by AM4283** [acxz/pkgbuilds#206] opened 2022-07-14 03:57 UTC
Hello,
I was receiving this error today when trying to install this package, as a dependency for the ```ros-noetic-python-qt-binding``` package, which in turn was a dependency for the ```ros-noetic-moveit``` package. 
```
[albi@archlaptop] ➜ ros-noetic-python-qt-binding (U! master) yay -S python-pyqt5-sip4 
:: Checking for conflicts... 
:: Checking for inner conflicts... 
 -> Package conflicts found: 
 -> Installing python-pyqt5-sip4 will remove: python-pyqt5 
 -> Conflicting packages will have to be confirmed manually 
[Aur:1]  python-pyqt5-sip4-5.15.6-2 
  1 python-pyqt5-sip4                (Build Files Exist) 
==> Packages to cleanBuild? 
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4) 
==> 
:: PKGBUILD up to date, Skipping (1/0): python-pyqt5-sip4 
  1 python-pyqt5-sip4                (Build Files Exist) 
==> Diffs to show? 
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4) 
==> 
:: (1/1) Parsing SRCINFO: python-pyqt5-sip4 
==> Making package: python-pyqt5-sip4 5.15.6-2 (Wed 13 Jul 2022 11:54:06 PM EDT) 
==> Retrieving sources... 
  -> Found PyQt5-5.15.6.tar.gz 
  -> Found restore-sip4-support.patch 
==> Validating source files with sha256sums... 
    PyQt5-5.15.6.tar.gz ... Passed 
    restore-sip4-support.patch ... Passed 
==> Making package: python-pyqt5-sip4 5.15.6-2 (Wed 13 Jul 2022 11:54:07 PM EDT) 
==> Checking runtime dependencies... 
==> Checking buildtime dependencies... 
==> Retrieving sources... 
  -> Found PyQt5-5.15.6.tar.gz 
  -> Found restore-sip4-support.patch 
==> Validating source files with sha256sums... 
    PyQt5-5.15.6.tar.gz ... Passed 
    restore-sip4-support.patch ... Passed 
==> Removing existing $srcdir/ directory... 
==> Extracting sources... 
  -> Extracting PyQt5-5.15.6.tar.gz with bsdtar 
==> Starting prepare()... 
patching file sip/QtCore/QtCoremod.sip 
==> Sources are ready. 
==> Making package: python-pyqt5-sip4 5.15.6-2 (Wed 13 Jul 2022 11:54:08 PM EDT) 
==> Checking runtime dependencies... 
==> Checking buildtime dependencies... 
==> WARNING: Using existing $srcdir/ tree 
==> Removing existing $pkgdir/ directory... 
==> Starting build()... 
Traceback (most recent call last): 
  File "/usr/bin/sip-build", line 33, in <module> 
    sys.exit(load_entry_point('sip==6.6.2', 'console_scripts', 'sip-build')()) 
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point 
    return next(matches).load() 
StopIteration 
==> ERROR: A failure occurred in build(). 
    Aborting... 
 -> error making: python-pyqt5-sip4 
```

**Comment by acxz** [comment] 2022-07-14 12:44
Duplicate of #175 

please search previous issues before posting yours

If you still need help, feel free to post on the above linked closed issue and we can take it from there.

**Closed by acxz** 2022-07-14 12:44 UTC
