### ISSUE TITLE
[openvsp] makepkg fails with "cannot stat 'python'"

### ISSUE THREAD

**Issue by aleksclark** [acxz/pkgbuilds#117] opened 2021-03-11 23:03 UTC
Attempting to build/install via yay produces the following
```
  inflating: OpenVSP-3.23.0-Linux/vspslicer  
cp: cannot stat 'python': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
Error making: openvsp
➜  ~ 
```

**Comment by acxz** [comment] 2021-07-01 22:38
I can't seem to reproduce this. Can you try again with the lastest update on the AUR?
If I don't hear a response, I'll close this issue within the week.

**Comment by busbuyukefe** [comment] 2021-07-10 15:44
`  inflating: OpenVSP-3.24.0-Linux/scripts/TestDXF.vspscript  
  inflating: OpenVSP-3.24.0-Linux/scripts/CreateEditGeom.vspscript  
  inflating: OpenVSP-3.24.0-Linux/scripts/SurfaceIntersection.vspscript  
cp: cannot stat 'python': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error making: openvsp
`

I am getting the same error too.

**Comment by x3oo** [comment] 2021-08-19 23:14
i get the same error. i googled that cp has sometime issues along those lines. explained here: 
https://askubuntu.com/questions/1338834/cp-cannot-stat-no-such-file-or-directory
https://www.it-swarm.com.de/de/linux/wie-verwendet-man-regulaere-ausdruecke-mit-dem-befehl-cp-unter-linux/959193822/
but i dont know enough about building packages to solve it.

**Comment by x3oo** [comment] 2021-08-19 23:28
there is a cp python command in the pkg build file. there doesnt seem to be a python folder which can be copied in that folder. thats where the error comes from. i commented the line out.

**Comment by x3oo** [comment] 2021-08-19 23:28
seems to work

**Comment by acxz** [comment] 2021-08-20 16:48
I believe I know what might be causing this issue. I have set `python` as an `optdepend` and if `python` is not present during the building of `openvsp` then the python folder will not be created to copy over.

I have moved the `python` optdep to the depends group. Let me know if this resolves the issue.

**Comment by x3oo** [comment] 2021-08-22 16:16
i do have python installed
maybe thats the reason it didnt need to be build and copied

**Comment by acxz** [comment] 2021-09-06 14:48
I see, since it seems like many people I have gone ahead and removed the `cp -r python` line. Sorry for delaying this. Please comment on this issue or open another if the problem persists.

**Closed by acxz** 2021-09-06 14:48 UTC
